export const ROUTE_PATHS = {
  home: '/',
  notifications: '/notifications',
  appointmentDetailBase: '/appointments/:id',
  booking: '/booking',
  bookingBranch: '/booking/branch',
  bookingServices: '/booking/services',
  bookingTechnician: '/booking/technician',
  promotions: '/promotions',
  promotionDetailBase: '/promotions/:id',
  services: '/services',
  gallery: '/gallery',
  profile: '/profile',
  login: '/login',
  auth: '/auth',
} as const
