export const ROUTE_PATHS = {
  home: '/',
  notifications: '/notifications',
  appointmentDetailBase: '/appointments/:id',
  appointmentCancelBase: '/appointments/:id/cancel',
  myAppointments: '/my-appointments',
  booking: '/booking',
  bookingBranch: '/booking/branch',
  bookingServices: '/booking/services',
  bookingTechnician: '/booking/technician',
  bookingSelectDate: '/booking/select-date',
  bookingConfirm: '/booking/confirm',
  bookingSuccess: '/booking/success',
  promotions: '/promotions',
  promotionDetailBase: '/promotions/:id',
  services: '/services',
  serviceDetailBase: '/services/:id',
  serviceReviewsBase: '/services/:id/reviews',
  reviews: '/reviews',
  gallery: '/gallery',
  nailDetailBase: '/gallery/:nailId',
  profile: '/profile',
  login: '/login',
  auth: '/auth',
} as const
